#!/usr/bin/env bash
# usage:
#
# ./ci-build-binary <binary>
#
# where <binary> is one of: sequencer, sequencer-sqlite, espresso-dev-node, other
#
set -euo pipefail

case "$1" in
    "sequencer")
        cargo build --locked --release --bin sequencer
        ;;
    "sequencer-sqlite")
        cargo build --locked --release --manifest-path ./sequencer-sqlite/Cargo.toml --target-dir ./target
        ;;
    "espresso-dev-node")
        cargo build --locked --release --features "embedded-db testing" --bin espresso-dev-node
        ;;
    "other")
        BINS="$(cargo metadata --no-deps --format-version 1 \
        | jq -r '.packages[].targets[] | select(.kind[] == "bin") | .name' \
        | grep -v '^sequencer$\|espresso-dev-node' \
        | xargs -I{} echo --bin {} \
        | tr '\n' ' ')"
        echo "Building other binaries: $BINS"
        cargo build --locked --release $BINS
        ;;
    *)
        echo "Unknown binary: $1"
        exit 1
        ;;
esac
