#!/usr/bin/env bash
#
# A script that we can use locally and in docker to run the upgrade proxy script
# with ts-node. The arguments are passed to the upgrade script.
#
# Usage: scripts/multisig-upgrade-entrypoint [args]
#
set -e
docker_path=/app/contracts/script/multisigTransactionProposals/safeSDK/upgradeProxy.ts

# 1. if the docker path exists use it
# 2. get repo path if the docker path does not exist and use that
# 3. otherwise error

if [ -f "$docker_path" ]; then
    echo "Using docker path: $docker_path"
    path=$docker_path
else
    REPO_ROOT=$(git rev-parse --show-toplevel)
    repo_path=$REPO_ROOT/contracts/script/multisigTransactionProposals/safeSDK/upgradeProxy.ts
    if [ -f "$repo_path" ]; then
        path=$repo_path
    else
        echo "Error: Neither $repo_path nor $docker_path exist."
        exit 1
    fi
fi

npx ts-node "$path" "$@"
